from src.violations.types import THZCategory, THZCategoryMatch


TTL_HOURS: int = 48
SCORING_WINDOW_DAYS: int = 365*3
CLASSIFICATION_CONCURRENCY_LIMIT: int = 10


THZ_CATEGORY_PRIORITY: tuple[THZCategory, ...] = tuple(THZCategory)

THZ_CATEGORY_META: dict[THZCategory, THZCategoryMatch] = {
    THZCategory.THZ_1: THZCategoryMatch(THZCategory.THZ_1.value, "Drunk Driving", 100),
    THZCategory.THZ_2: THZCategoryMatch(THZCategory.THZ_2.value, "Dangerous / Reckless Driving", 90),
    THZCategory.THZ_3: THZCategoryMatch(THZCategory.THZ_3.value, "Disobeying Police / Traffic Authority", 90),
    THZCategory.THZ_4: THZCategoryMatch(THZCategory.THZ_4.value, "Overspeeding / Racing", 80),
    THZCategory.THZ_5: THZCategoryMatch(THZCategory.THZ_5.value, "Driving without Licence or Insurance", 70),
    THZCategory.THZ_6: THZCategoryMatch(THZCategory.THZ_6.value, "Wrong Lane / Wrong Side Driving", 60),
    THZCategory.THZ_7: THZCategoryMatch(THZCategory.THZ_7.value, "Hazardous Goods Carriage Violation", 50),
    THZCategory.THZ_8: THZCategoryMatch(THZCategory.THZ_8.value, "Traffic Signal Violations", 50),
    THZCategory.THZ_9: THZCategoryMatch(THZCategory.THZ_9.value, "Overloading", 40),
    THZCategory.THZ_10: THZCategoryMatch(THZCategory.THZ_10.value, "Safety Measures (Helmet / Seatbelt)", 30),
    THZCategory.THZ_11: THZCategoryMatch(THZCategory.THZ_11.value, "Vehicle Modifications", 20),
    THZCategory.THZ_12: THZCategoryMatch(THZCategory.THZ_12.value, "Wrong Parking", 10),
}

# Rule-only v1 keyword inventory. Expand incrementally from production data.
THZ_KEYWORD_RULES: dict[THZCategory, tuple[str, ...]] = {
    THZCategory.THZ_1: (
        "alcohol",
        "alco test",
        "drink and drive",
        "drunk",
        "intoxicated",
        "liquor",
        "madya",
        "nashe",
        "sharab",
    ),
    THZCategory.THZ_2: (
        "beperwahi",
        "dangerous",
        "dhokadayak",
        "negligent",
        "rash",
        "rash driving",
        "reckless",
        "zig zag",
        "बेपरवाही",
        "बेपर्वा",
    ),
    THZCategory.THZ_3: (
        "आदेश का उल्लंघन",
        "compulsory turn",
        "disobey",
        "disobedience of any direction",
        "disobeying orders",
        "general offence",
        "hukam ullanghan",
        "lawful direction",
        "no entry",
        "no entry sign",
        "no left turn",
        "no right turn",
        "orders general",
        "police instruction",
        "refused",
        "stop signal ignored",
        "violation of mandatory signs",
        "violation of restriction of time",
        "नहीं माना",
    ),
    THZCategory.THZ_4: (
        "contravention of speed limits",
        "driving at excess speed",
        "excessive speed",
        "faster speed",
        "high speed",
        "lmv",
        "over speed",
        "over speeding",
        "overspeed",
        "race",
        "racing",
        "speed",
        "speed limit",
        "speeding",
        "तेज रफ्तार",
        "ઝડપ",
    ),
    THZCategory.THZ_5: (
        "बिना लाइसेंस",
        "driving licence not found",
        "driving vehicles without license",
        "driving without insurance",
        "insurance expired",
        "licence expired",
        "license nahi",
        "no insurance",
        "no licence",
        "no license",
        "puc on demand",
        "un-insured vehicles",
        "w/o insurance",
        "without license",
        "without licence",
        "without pollution certificate",
        "without pucc",
        "વિમા",
        "વીમા",
    ),
    THZCategory.THZ_6: (
        "against the authorized flow",
        "contra flow",
        "driving against the authorized flow of traffic",
        "lane change",
        "lane discipline",
        "one way traffic",
        "one way violation",
        "wrong lane",
        "wrong side",
        "wrong side driving",
        "गलत दिशा",
        "उल्टी दिशा",
        "ખોટી દિશા",
    ),
    THZCategory.THZ_7: (
        "chemical transport",
        "dangerous goods",
        "explosive material",
        "hazard sign missing",
        "hazardous",
        "hazmat",
        "खतरनाक पदार्थ",
        "જોખમી માલ",
    ),
    THZCategory.THZ_8: (
        "disobey of traffic signals",
        "jumped signal",
        "jumping red light",
        "लाल बत्ती",
        "red light",
        "rlvd",
        "road marking",
        "signal jump",
        "signal violation",
        "stop line",
        "traffic signal",
        "traffic signals",
        "violation of stop line",
        "zebra crossing",
        "સિગ્નલ",
        "சிக்னல்",
    ),
    THZCategory.THZ_9: (
        "अधिक भार",
        "capacity exceeded",
        "exceeding premissible weight",
        "excess load",
        "extra passenger",
        "goods carriage",
        "load projection",
        "notification",
        "overload",
        "overloading",
        "overloading of",
        "overloading of goods carriage",
        "ઓવરલોડ",
    ),
    THZCategory.THZ_10: (
        "बिना हेलमेट",
        "सीट बेल्ट",
        "child restraint",
        "driver w/o seat belt",
        "failure to use safety belt",
        "front passanger w/o seat belt",
        "helmet",
        "no helmet",
        "no use of seat belt",
        "not using seat-belt",
        "seat belt",
        "seatbelt",
        "without helmet",
        "without seat belt",
        "without wearing safety belt",
        "હેલ્મેટ",
        "ஹெல்மெட்",
    ),
    THZCategory.THZ_11: (
        "संशोधन",
        "air pollution",
        "altered body",
        "black film",
        "fancy number plate",
        "high security registration number plate",
        "hsrp",
        "illegal modification",
        "modification",
        "non compliance",
        "number plate",
        "number plate violation",
        "pressure horn",
        "rc violation",
        "silencer modified",
        "third number plate",
        "tinted glass",
        "visible smoke",
        "visual compliance",
        "મોડિફિકેશન",
    ),
    THZCategory.THZ_12: (
        "गलत पार्किंग",
        "improper parking",
        "improper or obstructive parking",
        "no parking",
        "no.parkeng",
        "obstructive parking",
        "parked in prohibited area",
        "parking",
        "parking improper",
        "parking violation",
        "tow away zone",
        "violation of parking rules",
        "wrong parking",
        "પાર્કિંગ",
        "பார்கிંગ",
    ),
}
