"""add max, min and avg speed columns in vehicle trips table

Revision ID: 10a510ec7a93
Revises: 963b5e5ffb08
Create Date: 2026-06-15 10:45:55.273433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a510ec7a93'
down_revision: Union[str, Sequence[str], None] = '963b5e5ffb08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_trips', sa.Column('max_speed_kmph', sa.Float(), nullable=True))
    op.add_column('vehicle_trips', sa.Column('min_speed_kmph', sa.Float(), nullable=True))
    op.add_column('vehicle_trips', sa.Column('avg_speed_kmph', sa.Float(), nullable=True))
    op.create_check_constraint(
        'ck_vehicle_trips_min_speed_kmph',
        'vehicle_trips',
        'min_speed_kmph IS NULL OR min_speed_kmph >= 2.0',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_vehicle_trips_min_speed_kmph', 'vehicle_trips', type_='check')
    op.drop_column('vehicle_trips', 'avg_speed_kmph')
    op.drop_column('vehicle_trips', 'min_speed_kmph')
    op.drop_column('vehicle_trips', 'max_speed_kmph')
    # ### end Alembic commands ###
