"""widen telematics string columns

Revision ID: 1b8e882789a5
Revises: 393a24f01d66
Create Date: 2026-06-11 08:44:55.749041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b8e882789a5'
down_revision: Union[str, Sequence[str], None] = '393a24f01d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telematics_events', 'header',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('telematics_events', 'vendor_id',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('telematics_events', 'vehicle_reg_no',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('telematics_events', 'operator_name',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('telematics_events', 'mcc',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=8),
               existing_nullable=True)
    op.alter_column('telematics_events', 'mnc',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=8),
               existing_nullable=True)
    op.alter_column('telematics_events', 'lac',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.alter_column('telematics_events', 'cell_id',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr1_lac',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr1_cell_id',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr1_signal_strength',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_comment='dBm',
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr2_lac',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr2_cell_id',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr2_signal_strength',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_comment='dBm',
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr3_lac',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr3_cell_id',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr3_signal_strength',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_comment='dBm',
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr4_lac',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr4_cell_id',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr4_signal_strength',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_comment='dBm',
               existing_nullable=True)
    op.alter_column('telematics_events', 'checksum',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_comment='32-bit CRC',
               existing_nullable=True)
    op.alter_column('telematics_events', 'ota_command',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telematics_events', 'ota_command',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('telematics_events', 'checksum',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_comment='32-bit CRC',
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr4_signal_strength',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_comment='dBm',
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr4_cell_id',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr4_lac',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr3_signal_strength',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_comment='dBm',
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr3_cell_id',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr3_lac',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr2_signal_strength',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_comment='dBm',
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr2_cell_id',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr2_lac',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr1_signal_strength',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_comment='dBm',
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr1_cell_id',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr1_lac',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    op.alter_column('telematics_events', 'cell_id',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    op.alter_column('telematics_events', 'lac',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    op.alter_column('telematics_events', 'mnc',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)
    op.alter_column('telematics_events', 'mcc',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)
    op.alter_column('telematics_events', 'operator_name',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    op.alter_column('telematics_events', 'vehicle_reg_no',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.alter_column('telematics_events', 'vendor_id',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.alter_column('telematics_events', 'header',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    # ### end Alembic commands ###
