"""first migration

Revision ID: 388e93fc9a83
Revises: 
Create Date: 2026-04-04 12:28:59.116603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '388e93fc9a83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vehicle_number', sa.String(length=16), nullable=False),
    sa.Column('challan_number', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(length=16), nullable=False),
    sa.Column('offense_details', sa.String(length=256), nullable=False),
    sa.Column('thz_category', sa.String(length=8), nullable=False),
    sa.Column('thz_description', sa.String(length=256), nullable=False),
    sa.Column('thz_deduction', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('challan_place', sa.String(length=256), nullable=True),
    sa.Column('challan_datetime', sa.TIMESTAMP(), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('rto', sa.String(length=64), nullable=True),
    sa.Column('accused_name', sa.String(length=64), nullable=True),
    sa.Column('fine_amount', sa.Integer(), nullable=True),
    sa.Column('challan_status', sa.String(length=64), nullable=True),
    sa.Column('court_challan', sa.Boolean(), nullable=False),
    sa.Column('court_name', sa.String(length=64), nullable=True),
    sa.Column('upstream_code', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('removed_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challan_number', 'source_id', name='_unique_challan_number')
    )
    op.create_index('ix_challans_vehicle_date', 'challans', ['vehicle_number', 'challan_datetime'], unique=False)
    op.create_table('challans_fetch_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vehicle_number', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.String(length=16), nullable=False),
    sa.Column('fetched_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_challan_fetch_logs_vehicle_fetched', 'challans_fetch_logs', ['vehicle_number', 'fetched_at'], unique=False)
    op.create_table('dashboard_users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index('ix_dashboard_users_email', 'dashboard_users', ['email'], unique=False)
    op.create_table('dbs_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vehicle_number', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_deductions', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('premium_modifier_pct', sa.Integer(), nullable=False),
    sa.Column('total_violations', sa.Integer(), nullable=False),
    sa.Column('severe_violations', sa.Integer(), nullable=False),
    sa.Column('moderate_violations', sa.Integer(), nullable=False),
    sa.Column('low_violations', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DATE(), nullable=False),
    sa.Column('window_end', sa.DATE(), nullable=False),
    sa.Column('last_violation_datetime', sa.TIMESTAMP(), nullable=True),
    sa.Column('computed_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dbs_records_vehicle_computed', 'dbs_records', ['vehicle_number', 'computed_at'], unique=False)
    op.create_table('vehicles',
    sa.Column('vehicle_number', sa.String(length=16), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('source_id', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('category_description', sa.String(length=255), nullable=True),
    sa.Column('chassis_number', sa.String(length=32), nullable=True),
    sa.Column('engine_number', sa.String(length=32), nullable=True),
    sa.Column('maker_description', sa.String(length=128), nullable=True),
    sa.Column('maker_model', sa.String(), nullable=True),
    sa.Column('fit_up_to', sa.Date(), nullable=True),
    sa.Column('manufacturing_date', sa.String(length=32), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('registered_at', sa.String(length=128), nullable=True, comment='Place of registration'),
    sa.Column('body_type', sa.String(length=64), nullable=True),
    sa.Column('fuel_type', sa.String(length=64), nullable=True),
    sa.Column('norms_type', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('cubic_capacity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vehicle_gross_weight', sa.Integer(), nullable=True),
    sa.Column('no_cylinders', sa.SmallInteger(), nullable=True),
    sa.Column('seat_capacity', sa.SmallInteger(), nullable=True),
    sa.Column('sleeper_capacity', sa.SmallInteger(), nullable=True),
    sa.Column('standing_capacity', sa.SmallInteger(), nullable=True),
    sa.Column('wheelbase', sa.Integer(), nullable=True),
    sa.Column('unladen_weight', sa.Integer(), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('present_address', sa.String(length=512), nullable=True),
    sa.Column('permanent_address', sa.String(length=512), nullable=True),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('financer', sa.String(length=128), nullable=True),
    sa.Column('financed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('insurance_company', sa.String(length=128), nullable=True),
    sa.Column('insurance_policy_number', sa.String(length=64), nullable=True),
    sa.Column('pucc_number', sa.String(length=64), nullable=True),
    sa.Column('pucc_upto', sa.Date(), nullable=True),
    sa.Column('permit_number', sa.String(length=64), nullable=True),
    sa.Column('permit_issue_date', sa.Date(), nullable=True),
    sa.Column('permit_type', sa.String(length=32), nullable=True),
    sa.Column('national_permit_number', sa.String(length=64), nullable=True),
    sa.Column('national_permit_issued_by', sa.String(length=128), nullable=True),
    sa.Column('blacklist_status', sa.String(length=64), nullable=True),
    sa.Column('noc_details', sa.String(length=256), nullable=True),
    sa.Column('owner_number', sa.SmallInteger(), nullable=True),
    sa.Column('rc_status', sa.String(length=64), nullable=True),
    sa.Column('rto_code', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('vehicle_number')
    )
    op.create_index('ix_vehicles_state_code', 'vehicles', ['state_code'], unique=False)
    op.create_table('challans_offense_details',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('challan_id', sa.UUID(), nullable=False),
    sa.Column('offense_name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challan_id'], ['challans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_challan_offenses_challan_id', 'challans_offense_details', ['challan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_challan_offenses_challan_id', table_name='challans_offense_details')
    op.drop_table('challans_offense_details')
    op.drop_index('ix_vehicles_state_code', table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index('ix_dbs_records_vehicle_computed', table_name='dbs_records')
    op.drop_table('dbs_records')
    op.drop_index('ix_dashboard_users_email', table_name='dashboard_users')
    op.drop_table('dashboard_users')
    op.drop_index('ix_challan_fetch_logs_vehicle_fetched', table_name='challans_fetch_logs')
    op.drop_table('challans_fetch_logs')
    op.drop_index('ix_challans_vehicle_date', table_name='challans')
    op.drop_table('challans')
    # ### end Alembic commands ###
