"""add checksum_matched col in telematics_events

Revision ID: 393a24f01d66
Revises: 6e475b9b4bc7
Create Date: 2026-06-11 06:53:09.532288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '393a24f01d66'
down_revision: Union[str, Sequence[str], None] = '6e475b9b4bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telematics_events', sa.Column('checksum_matched', sa.Boolean(), nullable=True, comment='True if computed checksum matches the received checksum'))
    op.alter_column('telematics_events', 'header',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telematics_events', 'header',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.drop_column('telematics_events', 'checksum_matched')
    # ### end Alembic commands ###
