"""widen_telematics_string_columns

Revision ID: 517b2a3ee0a5
Revises: 8ffb3a000877
Create Date: 2026-06-18 08:04:47.446136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '517b2a3ee0a5'
down_revision: Union[str, Sequence[str], None] = '8ffb3a000877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
