"""add nullable expires_at column in API keys

Revision ID: 681933dd6f3c
Revises: 9047316bc8b4
Create Date: 2026-06-24 10:52:06.866403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '681933dd6f3c'
down_revision: Union[str, Sequence[str], None] = '9047316bc8b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'expires_at')
    # ### end Alembic commands ###
