"""add telemetry fields columns in telematics events table

Revision ID: 6e475b9b4bc7
Revises: 8fe7c82c9380
Create Date: 2026-06-10 06:16:19.652471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e475b9b4bc7'
down_revision: Union[str, Sequence[str], None] = '8fe7c82c9380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telematics_events', sa.Column('header', sa.String(length=8), nullable=True))
    op.add_column('telematics_events', sa.Column('vendor_id', sa.String(length=16), nullable=True))
    op.add_column('telematics_events', sa.Column('firmware_version', sa.String(length=16), nullable=True))
    op.add_column('telematics_events', sa.Column('packet_type', sa.String(length=4), nullable=True))
    op.add_column('telematics_events', sa.Column('alert_id', sa.SmallInteger(), nullable=True))
    op.add_column('telematics_events', sa.Column('packet_status', sa.String(length=1), nullable=True, comment='L=Live, H=History'))
    op.add_column('telematics_events', sa.Column('imei', sa.String(length=15), nullable=True))
    op.add_column('telematics_events', sa.Column('vehicle_reg_no', sa.String(length=16), nullable=True))
    op.add_column('telematics_events', sa.Column('gps_fix', sa.Boolean(), nullable=True))
    op.add_column('telematics_events', sa.Column('gps_datetime', sa.DateTime(), nullable=True, comment='Combined GPS date and time in UTC (DDMMYYYY + hhmmss)'))
    op.add_column('telematics_events', sa.Column('latitude', sa.Float(), nullable=True, comment='Signed decimal degrees, negative=South'))
    op.add_column('telematics_events', sa.Column('longitude', sa.Float(), nullable=True, comment='Signed decimal degrees, negative=West'))
    op.add_column('telematics_events', sa.Column('speed', sa.Float(), nullable=True, comment='km/h'))
    op.add_column('telematics_events', sa.Column('heading', sa.Float(), nullable=True, comment='Course over ground in degrees (0-359.99)'))
    op.add_column('telematics_events', sa.Column('num_satellites', sa.SmallInteger(), nullable=True))
    op.add_column('telematics_events', sa.Column('altitude', sa.Float(), nullable=True, comment='Meters'))
    op.add_column('telematics_events', sa.Column('pdop', sa.Float(), nullable=True))
    op.add_column('telematics_events', sa.Column('hdop', sa.Float(), nullable=True))
    op.add_column('telematics_events', sa.Column('operator_name', sa.String(length=11), nullable=True))
    op.add_column('telematics_events', sa.Column('ignition', sa.Boolean(), nullable=True))
    op.add_column('telematics_events', sa.Column('main_power_status', sa.Boolean(), nullable=True, comment='0=disconnected, 1=reconnected'))
    op.add_column('telematics_events', sa.Column('main_input_voltage', sa.Float(), nullable=True, comment='Volts (7.0-40.0)'))
    op.add_column('telematics_events', sa.Column('internal_battery_voltage', sa.Float(), nullable=True, comment='Volts (0-4.2)'))
    op.add_column('telematics_events', sa.Column('emergency_status', sa.Boolean(), nullable=True))
    op.add_column('telematics_events', sa.Column('tamper_alert', sa.String(length=1), nullable=True, comment='C=Closed, O=Open'))
    op.add_column('telematics_events', sa.Column('gsm_signal_strength', sa.SmallInteger(), nullable=True, comment='0-31'))
    op.add_column('telematics_events', sa.Column('mcc', sa.String(length=4), nullable=True))
    op.add_column('telematics_events', sa.Column('mnc', sa.String(length=4), nullable=True))
    op.add_column('telematics_events', sa.Column('lac', sa.String(length=8), nullable=True))
    op.add_column('telematics_events', sa.Column('cell_id', sa.String(length=8), nullable=True))
    op.add_column('telematics_events', sa.Column('nmr1_lac', sa.String(length=8), nullable=True))
    op.add_column('telematics_events', sa.Column('nmr1_cell_id', sa.String(length=8), nullable=True))
    op.add_column('telematics_events', sa.Column('nmr1_signal_strength', sa.String(length=8), nullable=True, comment='dBm'))
    op.add_column('telematics_events', sa.Column('nmr2_lac', sa.String(length=8), nullable=True))
    op.add_column('telematics_events', sa.Column('nmr2_cell_id', sa.String(length=8), nullable=True))
    op.add_column('telematics_events', sa.Column('nmr2_signal_strength', sa.String(length=8), nullable=True, comment='dBm'))
    op.add_column('telematics_events', sa.Column('nmr3_lac', sa.String(length=8), nullable=True))
    op.add_column('telematics_events', sa.Column('nmr3_cell_id', sa.String(length=8), nullable=True))
    op.add_column('telematics_events', sa.Column('nmr3_signal_strength', sa.String(length=8), nullable=True, comment='dBm'))
    op.add_column('telematics_events', sa.Column('nmr4_lac', sa.String(length=8), nullable=True))
    op.add_column('telematics_events', sa.Column('nmr4_cell_id', sa.String(length=8), nullable=True))
    op.add_column('telematics_events', sa.Column('nmr4_signal_strength', sa.String(length=8), nullable=True, comment='dBm'))
    op.add_column('telematics_events', sa.Column('din_status', sa.String(length=4), nullable=True, comment='4-bit digital input status (DIN1-DIN4)'))
    op.add_column('telematics_events', sa.Column('dout_status', sa.String(length=2), nullable=True, comment='2-bit digital output status (DO1-DO2)'))
    op.add_column('telematics_events', sa.Column('device_mode', sa.SmallInteger(), nullable=True, comment='1=Active>0, 2=Active>0, 3=Sleep, 4=Deep sleep'))
    op.add_column('telematics_events', sa.Column('distance', sa.Float(), nullable=True, comment='Accumulated distance in km'))
    op.add_column('telematics_events', sa.Column('adc1', sa.Integer(), nullable=True, comment='mV'))
    op.add_column('telematics_events', sa.Column('adc2', sa.Integer(), nullable=True, comment='mV'))
    op.add_column('telematics_events', sa.Column('frame_number', sa.Integer(), nullable=True, comment='Sequence number (1-999999)'))
    op.add_column('telematics_events', sa.Column('ota_command', sa.String(length=64), nullable=True))
    op.add_column('telematics_events', sa.Column('checksum', sa.String(length=8), nullable=True, comment='32-bit CRC'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telematics_events', 'checksum')
    op.drop_column('telematics_events', 'ota_command')
    op.drop_column('telematics_events', 'frame_number')
    op.drop_column('telematics_events', 'adc2')
    op.drop_column('telematics_events', 'adc1')
    op.drop_column('telematics_events', 'distance')
    op.drop_column('telematics_events', 'device_mode')
    op.drop_column('telematics_events', 'dout_status')
    op.drop_column('telematics_events', 'din_status')
    op.drop_column('telematics_events', 'nmr4_signal_strength')
    op.drop_column('telematics_events', 'nmr4_cell_id')
    op.drop_column('telematics_events', 'nmr4_lac')
    op.drop_column('telematics_events', 'nmr3_signal_strength')
    op.drop_column('telematics_events', 'nmr3_cell_id')
    op.drop_column('telematics_events', 'nmr3_lac')
    op.drop_column('telematics_events', 'nmr2_signal_strength')
    op.drop_column('telematics_events', 'nmr2_cell_id')
    op.drop_column('telematics_events', 'nmr2_lac')
    op.drop_column('telematics_events', 'nmr1_signal_strength')
    op.drop_column('telematics_events', 'nmr1_cell_id')
    op.drop_column('telematics_events', 'nmr1_lac')
    op.drop_column('telematics_events', 'cell_id')
    op.drop_column('telematics_events', 'lac')
    op.drop_column('telematics_events', 'mnc')
    op.drop_column('telematics_events', 'mcc')
    op.drop_column('telematics_events', 'gsm_signal_strength')
    op.drop_column('telematics_events', 'tamper_alert')
    op.drop_column('telematics_events', 'emergency_status')
    op.drop_column('telematics_events', 'internal_battery_voltage')
    op.drop_column('telematics_events', 'main_input_voltage')
    op.drop_column('telematics_events', 'main_power_status')
    op.drop_column('telematics_events', 'ignition')
    op.drop_column('telematics_events', 'operator_name')
    op.drop_column('telematics_events', 'hdop')
    op.drop_column('telematics_events', 'pdop')
    op.drop_column('telematics_events', 'altitude')
    op.drop_column('telematics_events', 'num_satellites')
    op.drop_column('telematics_events', 'heading')
    op.drop_column('telematics_events', 'speed')
    op.drop_column('telematics_events', 'longitude')
    op.drop_column('telematics_events', 'latitude')
    op.drop_column('telematics_events', 'gps_datetime')
    op.drop_column('telematics_events', 'gps_fix')
    op.drop_column('telematics_events', 'vehicle_reg_no')
    op.drop_column('telematics_events', 'imei')
    op.drop_column('telematics_events', 'packet_status')
    op.drop_column('telematics_events', 'alert_id')
    op.drop_column('telematics_events', 'packet_type')
    op.drop_column('telematics_events', 'firmware_version')
    op.drop_column('telematics_events', 'vendor_id')
    op.drop_column('telematics_events', 'header')
    # ### end Alembic commands ###
