"""add response_duration_ms column in challan api fetch logs table

Revision ID: 859369050313
Revises: 45d913d335f5
Create Date: 2026-04-22 16:03:28.389015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '859369050313'
down_revision: Union[str, Sequence[str], None] = '45d913d335f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challans_fetch_logs', sa.Column('response_duration_ms', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challans_fetch_logs', 'response_duration_ms')
    # ### end Alembic commands ###
