"""add source ip and port columns in telematics events table

Revision ID: 8fe7c82c9380
Revises: 0f1d7b7e8c21
Create Date: 2026-06-03 10:45:26.601948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe7c82c9380'
down_revision: Union[str, Sequence[str], None] = '0f1d7b7e8c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
