"""widen telematics events columns

Revision ID: 8ffb3a000877
Revises: cc0101b656cc
Create Date: 2026-06-18 08:00:04.602945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ffb3a000877'
down_revision: Union[str, Sequence[str], None] = 'cc0101b656cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telematics_events', 'lac',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('telematics_events', 'cell_id',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr1_lac',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr1_cell_id',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr1_signal_strength',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_comment='dBm',
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr2_lac',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr2_cell_id',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr2_signal_strength',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_comment='dBm',
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr3_lac',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr3_cell_id',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr3_signal_strength',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_comment='dBm',
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr4_lac',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr4_cell_id',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr4_signal_strength',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_comment='dBm',
               existing_nullable=True)
    op.alter_column('telematics_events', 'checksum',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_comment='32-bit CRC',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telematics_events', 'checksum',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_comment='32-bit CRC',
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr4_signal_strength',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_comment='dBm',
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr4_cell_id',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr4_lac',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr3_signal_strength',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_comment='dBm',
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr3_cell_id',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr3_lac',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr2_signal_strength',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_comment='dBm',
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr2_cell_id',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr2_lac',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr1_signal_strength',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_comment='dBm',
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr1_cell_id',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.alter_column('telematics_events', 'nmr1_lac',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.alter_column('telematics_events', 'cell_id',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.alter_column('telematics_events', 'lac',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    # ### end Alembic commands ###
