"""add telematics devices table

Revision ID: 9047316bc8b4
Revises: 517b2a3ee0a5
Create Date: 2026-06-22 08:17:27.010304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9047316bc8b4'
down_revision: Union[str, Sequence[str], None] = '517b2a3ee0a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telematics_devices',
    sa.Column('imei', sa.String(length=15), nullable=False),
    sa.Column('vehicle_reg_no', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_source_ip', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('imei')
    )
    op.create_index('ix_telematics_devices_imei', 'telematics_devices', ['imei'], unique=False)
    op.create_index('ix_telematics_devices_vehicle_reg_no', 'telematics_devices', ['vehicle_reg_no'], unique=False)
    
    op.execute(
        sa.text(
            "INSERT INTO telematics_devices (imei, vehicle_reg_no, active) "
            "VALUES ('865510083289001', 'MH31CS1928', true)"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telematics_devices_vehicle_reg_no', table_name='telematics_devices')
    op.drop_index('ix_telematics_devices_imei', table_name='telematics_devices')
    op.drop_table('telematics_devices')
    # ### end Alembic commands ###
