"""use imei in telematics trip cursor

Revision ID: 963b5e5ffb08
Revises: cd648d294a02
Create Date: 2026-06-14 13:30:15.468416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '963b5e5ffb08'
down_revision: Union[str, Sequence[str], None] = 'cd648d294a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('telematics_trip_cursor_pkey', 'telematics_trip_cursor', type_='primary')
    op.add_column('telematics_trip_cursor', sa.Column('imei', sa.String(length=15), nullable=False))
    op.drop_column('telematics_trip_cursor', 'vehicle_reg_no')
    op.create_primary_key('telematics_trip_cursor_pkey', 'telematics_trip_cursor', ['imei'])
    op.add_column('vehicle_trips', sa.Column('imei', sa.String(length=15), nullable=True))
    op.create_index('ix_vehicle_trips_imei_started', 'vehicle_trips', ['imei', 'started_at'], unique=False)
    op.alter_column('vehicle_trips', 'vehicle_reg_no', existing_type=sa.String(length=32), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vehicle_trips_imei_started', table_name='vehicle_trips')
    op.drop_column('vehicle_trips', 'imei')
    op.drop_constraint('telematics_trip_cursor_pkey', 'telematics_trip_cursor', type_='primary')
    op.add_column('telematics_trip_cursor', sa.Column('vehicle_reg_no', sa.String(length=32), nullable=False))
    op.drop_column('telematics_trip_cursor', 'imei')
    op.create_primary_key('telematics_trip_cursor_pkey', 'telematics_trip_cursor', ['vehicle_reg_no'])
    # ### end Alembic commands ###