"""add overspeed instances column

Revision ID: bcea8c25373a
Revises: f5b9f5f4d2fd
Create Date: 2026-07-11 13:45:26.893145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcea8c25373a'
down_revision: Union[str, Sequence[str], None] = 'f5b9f5f4d2fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_trips', sa.Column('overspeeding_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_trips', 'overspeeding_count')
    # ### end Alembic commands ###
