"""add HA, HB and HT count columns in trips table

Revision ID: cc0101b656cc
Revises: 9da2f579782c
Create Date: 2026-06-17 18:59:41.649138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc0101b656cc'
down_revision: Union[str, Sequence[str], None] = '9da2f579782c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_trips', sa.Column('harsh_acceleration_count', sa.Integer(), nullable=True))
    op.add_column('vehicle_trips', sa.Column('harsh_braking_count', sa.Integer(), nullable=True))
    op.add_column('vehicle_trips', sa.Column('harsh_turning_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_trips', 'harsh_turning_count')
    op.drop_column('vehicle_trips', 'harsh_braking_count')
    op.drop_column('vehicle_trips', 'harsh_acceleration_count')
    # ### end Alembic commands ###
