"""add vehicle trips and trip cursor tables

Revision ID: cd648d294a02
Revises: 1b8e882789a5
Create Date: 2026-06-12 09:21:06.467056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd648d294a02'
down_revision: Union[str, Sequence[str], None] = '1b8e882789a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telematics_trip_cursor',
    sa.Column('vehicle_reg_no', sa.String(length=32), nullable=False),
    sa.Column('last_processed_event_id', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('open_trip_id', sa.UUID(), nullable=True),
    sa.Column('last_odometer_km', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('vehicle_reg_no')
    )
    op.create_table('vehicle_trips',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vehicle_reg_no', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'open'"), nullable=False),
    sa.Column('start_event_id', sa.BigInteger(), nullable=True),
    sa.Column('end_event_id', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=True),
    sa.Column('start_lon', sa.Float(), nullable=True),
    sa.Column('end_lat', sa.Float(), nullable=True),
    sa.Column('end_lon', sa.Float(), nullable=True),
    sa.Column('total_distance_km', sa.Float(), nullable=True),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('day_distance_km', sa.Float(), nullable=True),
    sa.Column('night_distance_km', sa.Float(), nullable=True),
    sa.Column('day_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('night_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('urban_distance_km', sa.Float(), nullable=True),
    sa.Column('rural_distance_km', sa.Float(), nullable=True),
    sa.Column('urban_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('rural_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('urban_rural_method', sa.String(length=16), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('elevation_loss_m', sa.Float(), nullable=True),
    sa.Column('hilly_distance_km', sa.Float(), nullable=True),
    sa.Column('flat_distance_km', sa.Float(), nullable=True),
    sa.Column('terrain_type', sa.String(length=8), nullable=True),
    sa.Column('parked_before_trip_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vehicle_trips_status', 'vehicle_trips', ['status'], unique=False)
    op.create_index('ix_vehicle_trips_vehicle_started', 'vehicle_trips', ['vehicle_reg_no', 'started_at'], unique=False)
    op.alter_column('telematics_events', 'ota_command',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('telematics_events', 'ota_command',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.drop_index('ix_vehicle_trips_vehicle_started', table_name='vehicle_trips')
    op.drop_index('ix_vehicle_trips_status', table_name='vehicle_trips')
    op.drop_table('vehicle_trips')
    op.drop_table('telematics_trip_cursor')
    # ### end Alembic commands ###
