"""add usage events table

Revision ID: de05a3d84e5f
Revises: 9fba80dc2a79
Create Date: 2026-05-12 18:16:06.346484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de05a3d84e5f'
down_revision: Union[str, Sequence[str], None] = '9fba80dc2a79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dashboard_user_id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('auth_type', sa.String(length=16), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('api_name', sa.String(length=64), nullable=False),
    sa.Column('usage_type', sa.String(length=8), nullable=False),
    sa.Column('vehicle_number', sa.String(length=16), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('from_db_cache', sa.Boolean(), nullable=False),
    sa.Column('challan_net_changes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_latency_ms', sa.Float(), nullable=False),
    sa.Column('vendor_challan_latency_ms', sa.Float(), nullable=True),
    sa.Column('vendor_rc_latency_ms', sa.Float(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('error_type', sa.String(length=64), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['dashboard_user_id'], ['dashboard_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_api_key_created', 'usage_events', ['api_key_id', sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('api_key_id IS NOT NULL'))
    op.create_index('idx_usage_created', 'usage_events', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_usage_dashboard_user_created', 'usage_events', ['dashboard_user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_usage_vehicle_number', 'usage_events', ['vehicle_number', sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('vehicle_number IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_usage_vehicle_number', table_name='usage_events', postgresql_where=sa.text('vehicle_number IS NOT NULL'))
    op.drop_index('idx_usage_dashboard_user_created', table_name='usage_events')
    op.drop_index('idx_usage_created', table_name='usage_events')
    op.drop_index('idx_usage_api_key_created', table_name='usage_events', postgresql_where=sa.text('api_key_id IS NOT NULL'))
    op.drop_table('usage_events')
    # ### end Alembic commands ###
